# Font configuration
font:
  # Normal font
  normal:
    family: Iosevka Nerd Font
    style: Regular
  # Bold font
  bold:
    family: Iosevka Nerd Font
    style: Bold
  # Italic font
  italic:
    family: Iosevka Nerd Font
    style: Italic
  # Bold italic font
  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic
  # Point size
  size: 13
